//! The .dsb flatbuffer schema — document format shared by file and wire roles (docs/design/dashbuf.md, docs/roadmap.md v2).
//!
//! Scope: a flattened node tree; fixed-size geometry plus the v0.2
//! flex layout vocabulary (mode NONE/H/V, per-axis hug/fill/fixed
//! sizing, gap, padding, alignment, min/max — docs/roadmap.md v0.2);
//! and the v0.3 paint vocabulary (docs/roadmap.md v0.3) held in a
//! document-level paint pool — solid fills, the four gradient kinds,
//! image fills, stroke with align, corner radii, clip. Schema source:
//! `schema/dashbuf.fbs`; Rust bindings are generated by `flatc` at
//! build time (see `build.rs`).
//!
//! Alongside the schema, [`container`] owns the `.dsb` file envelope — the
//! sectioned container that carries one or more of these flatbuffers plus raw
//! payload blobs in one file (`docs/design/dsb-container-format.md`), and
//! [`bank`] owns the assembly that fills one: a document plus the cold bank of
//! payloads one quality profile binds its assets to. [`cost`] is the byte
//! counter the startup-scaling criterion is measured with. The bytes a reader
//! reads come from one of two places, and the split is the target's: `map`
//! maps the file on a native host, and [`prefix`] reads the envelope out of a
//! fetched prefix where there is no mapping to make.
//!
//! # Two readers, and only one of them reads a payload
//!
//! [`open`] verifies the hot half of a file and hands back a [`Wanted`] per
//! asset entry — where the payload lies and what it must hash to. It reads no
//! payload byte, so under a mapping it faults in no blob page.
//! [`residency::Residency::touch`] is the only thing that turns a [`Wanted`]
//! into readable bytes, and it hashes them on the way
//! (`docs/decisions/verification-moves-from-open-to-touch.md`).
//!
//! [`open_verified`] is the eager reader: every payload hashed before it
//! returns, slices handed back. It is the right call for a tool checking a file
//! rather than drawing it — `dashc`'s CLI is exactly that — and for a test that
//! wants the whole file proven before it asserts anything. It is not
//! proportional to what is shown, and its name says so.
//!
//! [`prefetch`] is how a host decides which [`Wanted`]s to touch: the assets
//! one root's subtree draws, computed from the document and touching no payload
//! to decide.

pub mod bank;
pub mod container;
pub mod cost;
/// One memory mapping of a `.dsb` — native only; wasm reads a prefix instead.
#[cfg(not(target_arch = "wasm32"))]
pub mod map;
pub mod prefetch;
pub mod prefix;
pub mod residency;

#[allow(clippy::all, dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/dashbuf_generated.rs"));
}

pub use generated::dashbuf::*;

/// `Node.parent`'s "root node" sentinel.
pub const NO_PARENT: u32 = u32::MAX;
/// `Node.paint_entry`'s "draws nothing" sentinel.
pub const NO_PAINT: u32 = u32::MAX;
/// `Node.text`'s "no text content" sentinel.
pub const NO_TEXT: u32 = u32::MAX;
/// `Node.text_style`'s "unstyled text" sentinel.
pub const NO_TEXT_STYLE: u32 = u32::MAX;
/// `Paint.shape_field`'s "parametric shape" sentinel (story B1): the paint
/// entry carries the implicit rounded box, not a baked field.
pub const NO_FIELD: u32 = u32::MAX;

/// A payload the document names, as the file records it.
///
/// Both readers produce it — [`open`] over a whole file it holds, and
/// [`prefix::plan`] over an envelope read from a fetched prefix — and
/// [`residency::Residency::touch`] is the only thing that consumes it. One type
/// rather than one per reader, so a payload is proven by one rule wherever it
/// was read from (`docs/decisions/verification-moves-from-open-to-touch.md`
/// D7).
///
/// It is deliberately not bytes. A caller cannot hand this to a painter, which
/// is what turns "a painter must never receive bytes that have not been hashed"
/// from a rule someone has to remember into a thing that does not compile.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Wanted {
    /// The blob section it lives in, as an index into the file's section table.
    pub section: usize,
    /// Where it lies in the file — what a mapped host slices and a prefix host
    /// turns into a range request.
    pub range: std::ops::Range<u64>,
    /// What it must hash to. [`residency::Residency::touch`] checks it; a host
    /// caching payloads across loads can key on it, since it is the content's
    /// own name.
    pub hash: [u8; container::HASH_LEN],
}

/// Opens a `.dsb` file: the envelope, the ui document, and where each asset
/// payload lies — **without reading one**.
///
/// The reader a host that draws a document uses. It runs every check the format
/// promises over the hot half, in the order the container decision prescribes —
/// magic, version, bounds, the section table against the root hash, every
/// structured section's own content hash ([`container::Container::verify_hot`])
/// — then the flatbuffers verifier over the ui section, then the manifest and
/// its rows, and finally the **binding**: each `AssetEntry`'s canonical hash
/// mapped through the file's derivation manifest to a resident hash, and that
/// resolved to the blob section carrying it.
///
/// A file with no manifest section is the **null binding**, which is every RAW
/// file: a canonical hash resides as itself, and the mapping step is the
/// identity (`docs/decisions/derivation-manifest-section.md`).
///
/// The blob is resolved to its [`Wanted`] and stopped there. No payload byte is
/// read, so under a mapping this faults in the envelope and the structured
/// sections and no blob page at all — which is what R5 asks for and what
/// [`open_verified`] cannot give. Proving a payload is
/// [`residency::Residency::touch`]'s job, and [`prefetch`] is how a host decides
/// which ones a frame needs.
///
/// The returned list is one [`Wanted`] per asset entry, in entry order, and is
/// not deduplicated: two entries naming one payload are two identical entries
/// here, as they were two lookups before. That is the shape
/// `dashscene_core::load_document_mapped` takes, once each range a frame draws
/// has been touched.
///
/// The referential gate is still the caller's step, as it was before the
/// envelope: `dashscene_validator::validate_document` runs after this and
/// before loading.
///
/// [`bank::assemble`] is the write-side inverse: it resolves the same entry
/// hashes in the same order, in the other direction, and writes the manifest
/// this reads.
pub fn open(file: &[u8]) -> Result<(Document<'_>, Vec<Wanted>), OpenError> {
    let container = container::Container::parse(file)?;
    // Every structured section, which is every part of the file that is not a
    // blob. `ui_document` and `bindings_manifest` below each verify the one
    // section they read, so those two are hashed twice — a few kilobytes, over
    // the half of the file this reader is allowed to read, and the price of
    // keeping "exactly one ui section" stated in one place rather than
    // reimplemented here.
    container.verify_hot()?;
    let ui = container.ui_document()?;
    let document = root_as_document(ui)?;
    let manifest = bindings(&container)?;

    let wanted = document
        .assets()
        .unwrap_or_default()
        .iter()
        .map(|entry| {
            let canonical = entry.hash().bytes();
            let section = container.blob_index_by_hash(resident_of(&manifest, canonical))?;
            let blob = container.section(section);
            Ok(Wanted {
                section,
                range: blob.offset..blob.offset + blob.length,
                hash: blob.hash,
            })
        })
        .collect::<Result<Vec<_>, container::ContainerError>>()?;

    Ok((document, wanted))
}

/// [`open`]'s eager counterpart: every asset payload hashed before it returns,
/// and slices handed back rather than ranges.
///
/// The one call a reader that is **checking** a file rather than drawing it
/// needs, and the one that keeps the two halves of a document together. It runs
/// the same envelope and binding steps [`open`] runs, and then reads each blob
/// it resolves: [`container::Container::blob_by_hash`] hash-verifies before
/// returning, so every byte of every payload an entry names is read.
///
/// The returned payloads are in entry order, one per entry, which is the shape
/// `dashscene_core::load_document` takes. Nothing is copied: both the document
/// and the payloads borrow `file`.
///
/// **Nothing is copied is not nothing is read.** Under a mapping this faults in
/// every page holding a payload an entry names, which is what R5 says cold start
/// must not do. That is not a fault in this reader — it is what verifying a
/// whole file means — it is a reason not to use it to draw one. `dashc`'s CLI
/// checks files and is the caller this exists for; [`open`] is the one a host
/// draws through.
///
/// **It takes no [`cost::LoadCost`]**, and that is D8 rather than an omission
/// (`docs/decisions/verification-moves-from-open-to-touch.md`). This reader had
/// an instrumented sibling while the startup-scaling criterion measured the
/// owning path; story #598's re-run moved that measurement onto the mapped
/// path, leaving the sibling with no caller. The counter now records in exactly
/// two places — [`residency::Residency::touch_with_cost`] for a read and
/// `dashscene_core::load_document_bound_with_cost` for a copy — so what it
/// counts is what a load made resident, and a reader that hashes a whole file
/// on purpose cannot be mistaken for one.
pub fn open_verified(file: &[u8]) -> Result<(Document<'_>, Vec<&[u8]>), OpenError> {
    let container = container::Container::parse(file)?;
    let ui = container.ui_document()?;
    let document = root_as_document(ui)?;
    let manifest = bindings(&container)?;

    let payloads = document
        .assets()
        .unwrap_or_default()
        .iter()
        .map(|entry| {
            let canonical = entry.hash().bytes();
            let payload = container.blob_by_hash(resident_of(&manifest, canonical))?;
            Ok(payload)
        })
        .collect::<Result<Vec<_>, container::ContainerError>>()?;

    Ok((document, payloads))
}

/// One derivation-manifest row: the canonical hash an `AssetEntry` names, and
/// the content hash of the payload the file carries for it.
pub(crate) type BindingRow = ([u8; container::HASH_LEN], [u8; container::HASH_LEN]);

/// The file's derivation-manifest rows, verified and checked, or an empty list
/// when it carries no manifest section — the null binding.
///
/// Both hashes of every row are required to be [`container::HASH_LEN`] bytes,
/// and no canonical hash may appear twice. Neither is a shape
/// [`bank::assemble`] can produce, and both are refused rather than tolerated
/// because a row that cannot match anything is a claim silently doing nothing,
/// and a repeated canonical hash is two claims with no rule to choose between
/// them (P4).
fn bindings(container: &container::Container<'_>) -> Result<Vec<BindingRow>, OpenError> {
    binding_rows(container.bindings_manifest()?)
}

/// The manifest rows in `bytes`, or an empty list for [`None`] — the null
/// binding.
///
/// Split out from [`bindings`] so [`crate::prefix::plan`] resolves an asset by
/// the same rules over a manifest section it found in a hot run. The rules
/// themselves are stated on [`bindings`]; there is one implementation of them,
/// which is what keeps a prefix-loaded document and an `open`ed one from
/// disagreeing about what an asset resides as.
pub(crate) fn binding_rows(bytes: Option<&[u8]>) -> Result<Vec<BindingRow>, OpenError> {
    let Some(bytes) = bytes else {
        return Ok(Vec::new());
    };
    let manifest = flatbuffers::root::<AssetBindings<'_>>(bytes).map_err(OpenError::Bindings)?;

    let mut rows: Vec<BindingRow> = Vec::new();
    for (row, binding) in manifest.bindings().unwrap_or_default().iter().enumerate() {
        let pair = (binding.canonical().bytes(), binding.resident().bytes());
        let (Ok(canonical), Ok(resident)) = (pair.0.try_into(), pair.1.try_into()) else {
            return Err(OpenError::BindingHashLength {
                row,
                canonical: pair.0.len(),
                resident: pair.1.len(),
            });
        };
        if rows.iter().any(|(seen, _)| *seen == canonical) {
            return Err(OpenError::BindingRepeated { row });
        }
        rows.push((canonical, resident));
    }
    Ok(rows)
}

/// The hash the file carries `canonical` as: the manifest's mapping, or
/// `canonical` itself where the manifest has no row for it.
///
/// The absent row *is* the identity binding, which is what makes a RAW file and
/// a derived file one read path rather than two. A manifest row naming a
/// canonical hash no entry uses is inert by the same construction: resolution
/// is keyed by the entry's hash, so a row nothing asks for answers nothing.
pub(crate) fn resident_of<'a>(manifest: &'a [BindingRow], canonical: &'a [u8]) -> &'a [u8] {
    manifest
        .iter()
        .find(|(row, _)| row.as_slice() == canonical)
        .map_or(canonical, |(_, resident)| resident.as_slice())
}

/// Why a `.dsb` file could not be opened.
#[derive(Debug)]
pub enum OpenError {
    /// The envelope, the section table, or an asset's binding.
    Container(container::ContainerError),
    /// The ui section is not a structurally valid `Document`.
    Document(flatbuffers::InvalidFlatbuffer),
    /// The derivation-manifest section is not a structurally valid
    /// `AssetBindings`.
    Bindings(flatbuffers::InvalidFlatbuffer),
    /// A manifest row carries a hash that is not [`container::HASH_LEN`] bytes,
    /// so it could never match either an asset entry or a blob section.
    BindingHashLength {
        row: usize,
        canonical: usize,
        resident: usize,
    },
    /// A manifest row repeats a canonical hash an earlier row already bound.
    /// Two rows are two answers to what one asset resides as.
    BindingRepeated { row: usize },
}

impl From<container::ContainerError> for OpenError {
    fn from(error: container::ContainerError) -> Self {
        Self::Container(error)
    }
}

impl From<flatbuffers::InvalidFlatbuffer> for OpenError {
    fn from(error: flatbuffers::InvalidFlatbuffer) -> Self {
        Self::Document(error)
    }
}

impl std::fmt::Display for OpenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Container(error) => write!(f, "{error}"),
            Self::Document(error) => write!(f, "the ui section is not a valid document: {error}"),
            Self::Bindings(error) => write!(
                f,
                "the derivation-manifest section is not a valid binding table: {error}"
            ),
            Self::BindingHashLength {
                row,
                canonical,
                resident,
            } => write!(
                f,
                "derivation-manifest row {row} carries a {canonical}-byte canonical hash and \
                 a {resident}-byte resident hash; both must be 32 bytes"
            ),
            Self::BindingRepeated { row } => write!(
                f,
                "derivation-manifest row {row} repeats a canonical hash an earlier row \
                 already bound"
            ),
        }
    }
}

impl std::error::Error for OpenError {}
