//! The .dsb flatbuffer schema — document format shared by file and wire roles (DESIGN_1.md §5, §11 v2).
//!
//! v0.1 walking-skeleton scope: a flattened node tree, one layout mode
//! (fixed-size, no Taffy yet), one paint kind (solid fill). Schema
//! source: `schema/dashbuf.fbs`; Rust bindings are generated by `flatc`
//! at build time (see `build.rs`).

#[allow(clippy::all, dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/dashbuf_generated.rs"));
}

pub use generated::dashbuf::*;
