//! The .dsb flatbuffer schema — document format shared by file and wire roles (DESIGN_1.md §5, §11 v2).
//!
//! Scope: a flattened node tree, one layout mode (fixed-size, no Taffy
//! yet), and the v0.3 paint vocabulary (DESIGN_1.md §11 v0.3) held in a
//! document-level paint pool — solid fills, the four gradient kinds,
//! image fills, stroke with align, corner radii, clip. Schema source:
//! `schema/dashbuf.fbs`; Rust bindings are generated by `flatc` at
//! build time (see `build.rs`).

#[allow(clippy::all, dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/dashbuf_generated.rs"));
}

pub use generated::dashbuf::*;

/// `Node.parent`'s "root node" sentinel.
pub const NO_PARENT: u32 = u32::MAX;
/// `Node.paint_entry`'s "draws nothing" sentinel.
pub const NO_PAINT: u32 = u32::MAX;
/// `Node.text`'s "no text content" sentinel.
pub const NO_TEXT: u32 = u32::MAX;
/// `Node.text_style`'s "unstyled text" sentinel.
pub const NO_TEXT_STYLE: u32 = u32::MAX;
