/**
 * Boundary with `dashc_wasm.wasm` (crates/dashc, built via `just wasm`).
 *
 * Deno hands Figma REST JSON and the image bytes it resolved to the same Rust
 * code path the native `dashc` library call runs — Figma lowering,
 * `dashscene-validator` validation, `.dsb` emission — and gets back `.dsb`
 * bytes plus a diagnostics report, or a tagged failure. Same R6 rule either
 * way: an error blocks emission, never a silent drop (docs/decisions/figma-importer-deno-plus-dashc-wasm.md).
 *
 * The ABI is hand-written rather than generated by wasm-bindgen; the reasoning
 * is in `docs/decisions/dashc-wasm-abi.md`. Core WebAssembly has no string,
 * array, or object type — only numbers and one linear memory — so a boundary
 * like this one is always "allocate, copy in, pass a pointer and a length".
 * The only question is who writes that, and here it is this file.
 *
 * Wire format (little-endian, u32 lengths), mirrored in
 * `crates/dashc/src/abi/wire.rs`:
 *
 *   request   u32 profile | u32 json_len | json | u32 image_count
 *               | per image: u32 ref_len | ref | u32 format | u32 bytes_len | bytes
 *   response  u32 total | u32 status | u32 blob_len | blob | u32 json_len | json
 */

/** The paint-vocabulary subset a target honors (docs/design/architecture.md, R6). */
export type Profile = "core" | "full";

/** One encoded image asset. v0.3 knows exactly one container format. */
export interface ImageAsset {
  readonly format: "png";
  readonly bytes: Uint8Array;
}

/** What a diagnostic points at — a node, or a pooled entry by its own index. */
export type Location =
  | { readonly kind: "node"; readonly index: number; readonly path: string }
  | { readonly kind: "paintEntry"; readonly index: number }
  | { readonly kind: "imageAsset"; readonly index: number };

export interface Diagnostic {
  readonly rule: string;
  readonly severity: "warning" | "error";
  readonly at: Location;
  readonly message: string;
}

/**
 * A compile that produced a document. A warning does not block, so it rides
 * along with the bytes rather than being dropped (P4).
 */
export interface CompileOk {
  readonly bytes: Uint8Array;
  readonly diagnostics: readonly Diagnostic[];
}

/** Why a file could not be compiled at all — the four `CompileError` variants. */
export type CompileErrorDetail =
  | { readonly kind: "parse"; readonly message: string }
  | {
    readonly kind: "unsupported";
    readonly path: string;
    readonly what: string;
  }
  | {
    readonly kind: "unresolvedImage";
    readonly path: string;
    readonly imageRef: string;
  }
  | {
    readonly kind: "diagnostics";
    readonly diagnostics: readonly Diagnostic[];
  };

/** A compile that emitted nothing. R6: an error blocks the document. */
export class CompileFailed extends Error {
  readonly detail: CompileErrorDetail;

  constructor(detail: CompileErrorDetail) {
    super(describe(detail));
    this.name = "CompileFailed";
    this.detail = detail;
  }
}

function describe(detail: CompileErrorDetail): string {
  switch (detail.kind) {
    case "parse":
      return `not valid Figma REST JSON: ${detail.message}`;
    case "unsupported":
      return `${detail.path}: ${detail.what} is not in the v0.3 vocabulary`;
    case "unresolvedImage":
      return `${detail.path}: no image supplied for imageRef ${detail.imageRef}`;
    case "diagnostics":
      return detail.diagnostics
        .map((d) => `${d.severity}[${d.rule}]: ${d.message}`)
        .join("\n");
  }
}

/** The wire format this file speaks. `dashc_abi_version` must agree. */
const ABI_VERSION = 1;

const STATUS_OK = 0;
const STATUS_COMPILE_ERROR = 1;
const STATUS_MALFORMED_REQUEST = 2;

const PROFILE: Record<Profile, number> = { core: 0, full: 1 };
const FORMAT: Record<ImageAsset["format"], number> = { png: 0 };

/** Where `just wasm` puts the module. */
const DEFAULT_MODULE = new URL(
  "../../../target/wasm32-unknown-unknown/release/dashc_wasm.wasm",
  import.meta.url,
);

interface Exports {
  readonly memory: WebAssembly.Memory;
  readonly dashc_abi_version: () => number;
  readonly dashc_alloc: (len: number) => number;
  readonly dashc_free: (ptr: number, len: number) => void;
  readonly dashc_compile_figma: (ptr: number, len: number) => number;
  readonly dashc_figma_image_refs: (ptr: number, len: number) => number;
}

/** A framed response, decoded. */
interface Response {
  readonly status: number;
  readonly blob: Uint8Array;
  readonly json: string;
}

/**
 * Builds a request buffer, one length-prefixed field at a time.
 *
 * Chunks are held by reference and copied exactly once, in `finish`. A real
 * image asset is megabytes; appending it byte by byte into a `number[]` would
 * box every byte and copy the whole thing twice, and the tests — whose fixture
 * image is 69 bytes — would never show it.
 */
class Writer {
  #chunks: Uint8Array[] = [];
  #length = 0;

  u32(value: number): void {
    const field = new Uint8Array(4);
    new DataView(field.buffer).setUint32(0, value, true);
    this.#append(field);
  }

  bytes(value: Uint8Array): void {
    this.u32(value.length);
    this.#append(value);
  }

  text(value: string): void {
    this.bytes(new TextEncoder().encode(value));
  }

  finish(): Uint8Array {
    const out = new Uint8Array(this.#length);
    let at = 0;
    for (const chunk of this.#chunks) {
      out.set(chunk, at);
      at += chunk.length;
    }
    return out;
  }

  #append(chunk: Uint8Array): void {
    this.#chunks.push(chunk);
    this.#length += chunk.length;
  }
}

export class Dashc {
  readonly #exports: Exports;

  constructor(exports: Exports) {
    this.#exports = exports;
  }

  /**
   * Compiles Figma REST JSON into a `.dsb`.
   *
   * `images` maps every `imageRef` the lowering demands — ask
   * {@link Dashc.figmaImageRefs} — to its bytes. `dashc` does no I/O, because
   * it compiles to wasm, so resolving a ref is the caller's job by
   * construction.
   *
   * @throws {CompileFailed} when the document is blocked (R6).
   */
  compileFigma(
    json: string,
    profile: Profile,
    images: ReadonlyMap<string, ImageAsset>,
  ): CompileOk {
    const writer = new Writer();
    writer.u32(PROFILE[profile]);
    writer.text(json);
    writer.u32(images.size);
    for (const [imageRef, asset] of images) {
      writer.text(imageRef);
      writer.u32(FORMAT[asset.format]);
      writer.bytes(asset.bytes);
    }

    const response = this.#call(
      this.#exports.dashc_compile_figma,
      writer.finish(),
    );

    switch (response.status) {
      case STATUS_OK:
        return {
          bytes: response.blob,
          diagnostics: (JSON.parse(response.json) as {
            diagnostics: Diagnostic[];
          }).diagnostics,
        };
      case STATUS_COMPILE_ERROR:
        throw new CompileFailed(
          JSON.parse(response.json) as CompileErrorDetail,
        );
      default:
        throw new Error(malformed(response));
    }
  }

  /**
   * The `imageRef`s a lowering of this file will demand.
   *
   * Asked rather than scanned: a second copy of "where an imageRef lives in
   * Figma's shape", written here, could drift from the walk in `dashc` that
   * actually consumes them (P5).
   *
   * @throws {CompileFailed} when the file cannot be lowered at all.
   */
  figmaImageRefs(json: string): string[] {
    const response = this.#call(
      this.#exports.dashc_figma_image_refs,
      new TextEncoder().encode(json),
    );

    switch (response.status) {
      case STATUS_OK:
        return JSON.parse(response.json) as string[];
      case STATUS_COMPILE_ERROR:
        throw new CompileFailed(
          JSON.parse(response.json) as CompileErrorDetail,
        );
      default:
        throw new Error(malformed(response));
    }
  }

  /**
   * One round trip: reserve, write, call, read, release.
   *
   * `memory.buffer` is re-read after every call into the module. An allocation
   * can grow the memory, and growth detaches the previous ArrayBuffer — a view
   * held across a call would throw on access.
   */
  #call(
    exported: (ptr: number, len: number) => number,
    request: Uint8Array,
  ): Response {
    const { dashc_alloc, dashc_free, memory } = this.#exports;

    const requestPtr = dashc_alloc(request.length);
    if (requestPtr === 0 && request.length > 0) {
      throw new Error("dashc.wasm: the request allocation failed");
    }
    let responsePtr = 0;
    let total = 0;
    try {
      new Uint8Array(memory.buffer, requestPtr, request.length).set(request);

      responsePtr = exported(requestPtr, request.length);
      if (responsePtr === 0) {
        throw new Error("dashc.wasm: the response allocation failed");
      }

      total = new DataView(memory.buffer, responsePtr, 4).getUint32(0, true);

      // Copied out of linear memory (slice, not subarray) before anything can
      // grow it: the caller keeps these bytes long after the buffer is freed.
      const envelope = new Uint8Array(memory.buffer, responsePtr + 4, total)
        .slice();
      return decode(envelope);
    } finally {
      if (requestPtr !== 0) dashc_free(requestPtr, request.length);
      if (responsePtr !== 0) dashc_free(responsePtr, 4 + total);
    }
  }
}

function decode(envelope: Uint8Array): Response {
  const view = new DataView(
    envelope.buffer,
    envelope.byteOffset,
    envelope.byteLength,
  );

  const status = view.getUint32(0, true);
  const blobLen = view.getUint32(4, true);
  const blob = envelope.slice(8, 8 + blobLen);
  const jsonLen = view.getUint32(8 + blobLen, true);
  const jsonAt = 8 + blobLen + 4;
  const json = new TextDecoder().decode(
    envelope.subarray(jsonAt, jsonAt + jsonLen),
  );

  return { status, blob, json };
}

function malformed(response: Response): string {
  if (response.status === STATUS_MALFORMED_REQUEST) {
    // The two codecs disagree about the wire format. That is a bug in this file
    // or in crates/dashc/src/abi/wire.rs — never bad user input.
    return `dashc.wasm rejected the request as malformed: ${response.json}`;
  }
  return `dashc.wasm returned an unknown status ${response.status}`;
}

/**
 * Instantiates the module and checks that it speaks this wire format.
 *
 * A version mismatch, or a `.wasm` that exports nothing at all (which is what
 * the cdylib was before story #17), fails here with a sentence naming
 * `just wasm` — rather than misdecoding somewhere deep inside a test.
 */
export async function loadDashc(url: URL = DEFAULT_MODULE): Promise<Dashc> {
  let instance: WebAssembly.Instance;
  try {
    const bytes = await Deno.readFile(url);
    ({ instance } = await WebAssembly.instantiate(bytes, {}));
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(
      `cannot load ${url.pathname}: ${message} — run \`just wasm\` to build it`,
    );
  }

  const exports = instance.exports as unknown as Exports;
  if (typeof exports.dashc_abi_version !== "function") {
    throw new Error(
      `${url.pathname} exports no dashc ABI — run \`just wasm\` to rebuild it`,
    );
  }
  // Every call reads and writes this. Checking it here is what keeps a module
  // built with, say, an imported memory from failing later as an opaque
  // "cannot read properties of undefined" from inside a codec.
  if (!(exports.memory instanceof WebAssembly.Memory)) {
    throw new Error(
      `${url.pathname} exports no linear memory — run \`just wasm\` to ` +
        "rebuild it",
    );
  }

  const version = exports.dashc_abi_version();
  if (version !== ABI_VERSION) {
    throw new Error(
      `${url.pathname} speaks ABI version ${version}, this importer speaks ` +
        `${ABI_VERSION} — run \`just wasm\` to rebuild it`,
    );
  }

  return new Dashc(exports);
}
